customhost = "assignment.cfu1swm9jldz.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "assignment"
custombucket = "chanjunkai-student"
customregion = "us-east-1"